const categories = [
    { id: '전체',              label: '전체' },
    { id: '보안등주',          label: '보안등주' },
    { id: '가로등주',          label: '가로등주' },
    { id: '경관조명',          label: '경관조명' },
    { id: '열주등',            label: '열주등' },
    { id: '볼라드',            label: '볼라드' },
    { id: '태양광가로등',      label: '태양광가로등' },
    { id: '가오스형(스텐기본)', label: '가오스형(스텐기본)' },
    { id: '글로브형(스텐기본)', label: '글로브형(스텐기본)' },
];

const products = [
    // 보안등주 (투광등 + 횡단보도등)
    { id: 'HK-FLC06',   name: 'HK-FLC06',   category: '보안등주', image: './images/투광등/HK-FLC06.jpg' },
    { id: 'HK-FLC24',   name: 'HK-FLC24',   category: '보안등주', image: './images/투광등/HK-FLC24.jpg' },
    { id: 'HK-FLC30',   name: 'HK-FLC30',   category: '보안등주', image: './images/투광등/HK-FLC30.jpg' },
    { id: 'HK-FLC350',  name: 'HK-FLC350',  category: '보안등주', image: './images/투광등/HK-FLC350.jpg' },
    { id: 'HK-FLC640',  name: 'HK-FLC640',  category: '보안등주', image: './images/투광등/HK-FLC640.jpg' },
    { id: 'HK-FLC72',   name: 'HK-FLC72',   category: '보안등주', image: './images/투광등/HK-FLC72.jpg' },
    { id: 'HK-G35',     name: 'HK-G35',     category: '보안등주', image: './images/투광등/HK-G35.jpg' },
    { id: 'HK-SL100W',  name: 'HK-SL100W',  category: '보안등주', image: './images/투광등/HK-SL100W.jpg' },
    { id: 'HK-SL150W',  name: 'HK-SL150W',  category: '보안등주', image: './images/투광등/HK-SL150W.jpg' },
    { id: 'HK-SL-250W', name: 'HK-SL-250W', category: '보안등주', image: './images/투광등/HK-SL-250W.jpg' },
    { id: 'HK-HB-R120',  name: 'HK-HB-R120',  category: '보안등주', image: './images/횡단보도등/HK-HB-R120.jpg' },
    { id: 'HK-HB-R160',  name: 'HK-HB-R160',  category: '보안등주', image: './images/횡단보도등/HK-HB-R160.jpg' },
    { id: 'HK-HB-R200',  name: 'HK-HB-R200',  category: '보안등주', image: './images/횡단보도등/HK-HB-R200.jpg' },
    { id: 'HK-HB-R80',   name: 'HK-HB-R80',   category: '보안등주', image: './images/횡단보도등/HK-HB-R80.jpg' },
    { id: 'HK-HB-SQ100', name: 'HK-HB-SQ100', category: '보안등주', image: './images/횡단보도등/HK-HB-SQ100.jpg' },

    // 가로등주 (공원등 + 공원등ARM)
    { id: 'HK-PO-50',     name: 'HK-PO-50',     category: '가로등주', image: './images/공원등/HK-PO-50.jpg' },
    { id: 'HK-PO-60',     name: 'HK-PO-60',     category: '가로등주', image: './images/공원등/HK-PO-60.png' },
    { id: 'HK-PO-CS100',  name: 'HK-PO-CS100',  category: '가로등주', image: './images/공원등/HK-PO-CS100.png' },
    { id: 'HK-PO-GO60',   name: 'HK-PO-GO60',   category: '가로등주', image: './images/공원등/HK-PO-GO60.jpg' },
    { id: 'HK-PO-GO60A',  name: 'HK-PO-GO60A',  category: '가로등주', image: './images/공원등/HK-PO-GO60A.jpg' },
    { id: 'HK-PO-MR100',  name: 'HK-PO-MR100',  category: '가로등주', image: './images/공원등/HK-PO-MR100.jpg' },
    { id: 'HK-PO-MR50',   name: 'HK-PO-MR50',   category: '가로등주', image: './images/공원등/HK-PO-MR50.jpg' },
    { id: 'HK-PO-OG100',  name: 'HK-PO-OG100',  category: '가로등주', image: './images/공원등/HK-PO-OG100.jpg' },
    { id: 'HK-PO-OG50',   name: 'HK-PO-OG50',   category: '가로등주', image: './images/공원등/HK-PO-OG50.jpg' },
    { id: 'HK-PO-RS50R',  name: 'HK-PO-RS50R',  category: '가로등주', image: './images/공원등/HK-PO-RS50R.jpg' },
    { id: 'HK-PO-SQ50',   name: 'HK-PO-SQ50',   category: '가로등주', image: './images/공원등/HK-PO-SQ50.jpg' },
    { id: 'HK-PO-SQ50-1', name: 'HK-PO-SQ50-1', category: '가로등주', image: './images/공원등/HK-PO-SQ50-1.jpg' },
    { id: 'HK-PO-SQ50-2', name: 'HK-PO-SQ50-2', category: '가로등주', image: './images/공원등/HK-PO-SQ50-2.jpg' },
    { id: 'HK-PO-WJ60',   name: 'HK-PO-WJ60',   category: '가로등주', image: './images/공원등/HK-PO-WJ60.jpg' },
    { id: 'HK-PO-WJ60-1', name: 'HK-PO-WJ60-1', category: '가로등주', image: './images/공원등/HK-PO-WJ60-1.jpg' },
    { id: 'HK-PO-WJD50',  name: 'HK-PO-WJD50',  category: '가로등주', image: './images/공원등/HK-PO-WJD50.jpg' },
    { id: 'HK-PO-Z100',   name: 'HK-PO-Z100',   category: '가로등주', image: './images/공원등/HK-PO-Z100.jpg' },
    { id: 'HK-PO-Z50',    name: 'HK-PO-Z50',    category: '가로등주', image: './images/공원등/HK-PO-Z50.jpg' },
    { id: 'HK-OGA100',    name: 'HK-OGA100',    category: '가로등주', image: './images/공원등ARM/HK-OGA100.png' },
    { id: 'HK-OGA50',     name: 'HK-OGA50',     category: '가로등주', image: './images/공원등ARM/HK-OGA50.png' },

    // 경관조명
    { id: 'HK-B18',      name: 'HK-B18',      category: '경관조명', image: './images/라인바조명/HK-B18.jpg' },
    { id: 'HK-B36',      name: 'HK-B36',      category: '경관조명', image: './images/라인바조명/HK-B36.jpg' },
    { id: 'HK-B54',      name: 'HK-B54',      category: '경관조명', image: './images/라인바조명/HK-B54.jpg' },
    { id: 'HK-BO.5-7',   name: 'HK-BO.5-7',   category: '경관조명', image: './images/라인바조명/HK-BO.5-7.jpg' },
    { id: 'HK-BUGL15',   name: 'HK-BUGL15',   category: '경관조명', image: './images/라인바조명/HK-BUGL15.jpg' },
    { id: 'HK-HR70',     name: 'HK-HR70',     category: '경관조명', image: './images/라인바조명/HK-HR70.jpg' },
    { id: 'HK-MB12',     name: 'HK-MB12',     category: '경관조명', image: './images/라인바조명/HK-MB12.jpg' },
    { id: 'HK-MB15',     name: 'HK-MB15',     category: '경관조명', image: './images/라인바조명/HK-MB15.jpg' },
    { id: 'HK-LASER20',  name: 'HK-LASER20',  category: '경관조명', image: './images/반딧불레이저/HK-LASER20.jpg' },
    { id: 'HK-BWL6',     name: 'HK-BWL6',     category: '경관조명', image: './images/벽부,스텝매입등/HK-BWL6.jpg' },
    { id: 'HK-ST05',     name: 'HK-ST05',     category: '경관조명', image: './images/벽부,스텝매입등/HK-ST05.jpg' },
    { id: 'HK-LSR.24',   name: 'HK-LSR.24',   category: '경관조명', image: './images/장미,갈대조명/HK-LSR.24.jpg' },
    { id: 'HK-LSR.72R',  name: 'HK-LSR.72R',  category: '경관조명', image: './images/장미,갈대조명/HK-LSR.72R.jpg' },
    { id: 'HK-RL01',     name: 'HK-RL01',     category: '경관조명', image: './images/장미,갈대조명/HK-RL01.jpg' },
    { id: 'HK-UGL05',    name: 'HK-UGL05',    category: '경관조명', image: './images/지중매입등/HK-UGL05.jpg' },
    { id: 'HK-UGL06',    name: 'HK-UGL06',    category: '경관조명', image: './images/지중매입등/HK-UGL06.jpg' },
    { id: 'HK-UGL12',    name: 'HK-UGL12',    category: '경관조명', image: './images/지중매입등/HK-UGL12.jpg' },
    { id: 'HK-UGL24',    name: 'HK-UGL24',    category: '경관조명', image: './images/지중매입등/HK-UGL24.jpg' },
    { id: 'HK-UGL36',    name: 'HK-UGL36',    category: '경관조명', image: './images/지중매입등/HK-UGL36.jpg' },
    { id: 'HK-CL40-1.5', name: 'HK-CL40-1.5', category: '경관조명', image: './images/포인트조명/HK-CL40-1.5.jpg' },
    { id: 'HK-PL09',     name: 'HK-PL09',     category: '경관조명', image: './images/포인트조명/HK-PL09.jpg' },
    { id: 'HK-ST03',     name: 'HK-ST03',     category: '경관조명', image: './images/포인트조명/HK-ST03.jpg' },

    // 열주등
    { id: 'HK-J-DC51', name: 'HK-J-DC51', category: '열주등', image: './images/열주등/HK-J-DC51.jpg' },
    { id: 'HK-J-DC86', name: 'HK-J-DC86', category: '열주등', image: './images/열주등/HK-J-DC86.jpg' },
    { id: 'HK-J-GK96', name: 'HK-J-GK96', category: '열주등', image: './images/열주등/HK-J-GK96.jpg' },
    { id: 'HK-J-JY98', name: 'HK-J-JY98', category: '열주등', image: './images/열주등/HK-J-JY98.jpg' },
    { id: 'HK-J-NH90', name: 'HK-J-NH90', category: '열주등', image: './images/열주등/HK-J-NH90.jpg' },
    { id: '하트게이트', name: '하트게이트', category: '열주등', image: './images/열주등/하트게이트.jpg' },

    // 볼라드
    { id: 'HK-BOL-AD15',      name: 'HK-BOL-AD15',      category: '볼라드', image: './images/볼라드/HK-BOL-AD15.jpg' },
    { id: 'HK-BOL-AD15-1',    name: 'HK-BOL-AD15-1',    category: '볼라드', image: './images/볼라드/HK-BOL-AD15-1.jpg' },
    { id: 'HK-BOL-AD15-2',    name: 'HK-BOL-AD15-2',    category: '볼라드', image: './images/볼라드/HK-BOL-AD15-2.jpg' },
    { id: 'HK-BOL-AD30',      name: 'HK-BOL-AD30',      category: '볼라드', image: './images/볼라드/HK-BOL-AD30.jpg' },
    { id: 'HK-BOL-SSQ13.5',   name: 'HK-BOL-SSQ13.5',   category: '볼라드', image: './images/볼라드/HK-BOL-SSQ13.5.jpg' },
    { id: 'HK-BOL-SSQ30',     name: 'HK-BOL-SSQ30',     category: '볼라드', image: './images/볼라드/HK-BOL-SSQ30.jpg' },
    { id: 'HK-BOL-SSR10.5',   name: 'HK-BOL-SSR10.5',   category: '볼라드', image: './images/볼라드/HK-BOL-SSR10.5.jpg' },
    { id: 'HK-BOL-SSR20',     name: 'HK-BOL-SSR20',     category: '볼라드', image: './images/볼라드/HK-BOL-SSR20.jpg' },
    { id: 'HK-BOL-WS10.5',    name: 'HK-BOL-WS10.5',    category: '볼라드', image: './images/볼라드/HK-BOL-WS10.5.jpg' },
    { id: 'HK-BOL-WSQ13.5',   name: 'HK-BOL-WSQ13.5',   category: '볼라드', image: './images/볼라드/HK-BOL-WSQ13.5.jpg' },
    { id: 'HK-BOL-WSQ13.5-1', name: 'HK-BOL-WSQ13.5-1', category: '볼라드', image: './images/볼라드/HK-BOL-WSQ13.5-1.jpg' },

    // 태양광가로등
    { id: 'JW-SO165101',      name: 'JW-SO165101',  category: '태양광가로등', image: './images/태양광가로등/(1)JW-SO165101-30Li,30W,4m.png' },
    { id: 'JW-SO127',         name: 'JW-SO127',     category: '태양광가로등', image: './images/태양광가로등/(2)JW-SO127-50Li,50W,5m.png' },
    { id: 'JW-SO127G',        name: 'JW-SO127G',    category: '태양광가로등', image: './images/태양광가로등/(3)JW-SO127G-50Li,50W,5m.png' },
    { id: 'JW-SO165127',      name: 'JW-SO165127',  category: '태양광가로등', image: './images/태양광가로등/(4)JW-SO165127-50Li,50W,5m.png' },
    { id: 'JW-SO216127-50W',  name: 'JW-SO216127',  category: '태양광가로등', image: './images/태양광가로등/(5)JW-SO216127-50Li,50W,5m.png', drawing: './images/태양광가로등/JW-SO216127-drawing.jpg' },
    { id: 'JW-SO216127-60W',  name: 'JW-SO216127',  category: '태양광가로등', image: './images/태양광가로등/(6)JW-SO216127-60Li,60W,5m.png', drawing: './images/태양광가로등/JW-SO216127-drawing.jpg' },
    { id: 'JW-SO216127G-50W', name: 'JW-SO216127G', category: '태양광가로등', image: './images/태양광가로등/(7)JW-SO216127G-50Li,50W,5M.png' },
    { id: 'JW-SO216127G-60W', name: 'JW-SO216127G', category: '태양광가로등', image: './images/태양광가로등/(8)JW-SO216127G-60Li,60W,5M.png' },
    { id: 'JW-SO216127-100W', name: 'JW-SO216127',  category: '태양광가로등', image: './images/태양광가로등/(9)JW-SO216127-100Li,100W,7m.png', drawing: './images/태양광가로등/JW-SO216127-drawing.jpg' },
    { id: 'example_01',       name: 'example_01',   category: '태양광가로등', image: './images/태양광가로등/example_01.png' },

    // 가오스형(스텐기본)
    {
        id: '가오스형-스텐기본',
        name: '가오스형(스텐기본)',
        category: '가오스형(스텐기본)',
        image: './images/가오스형(스텐기본)/JW-P-01.png',
        images: [
            './images/가오스형(스텐기본)/JW-P-01.png',
            './images/가오스형(스텐기본)/JW-P-02.png',
            './images/가오스형(스텐기본)/JW-P-03.png',
            './images/가오스형(스텐기본)/JW-P-04.png',
            './images/가오스형(스텐기본)/JW-P-05.png',
            './images/가오스형(스텐기본)/JW-P-06.png',
            './images/가오스형(스텐기본)/JW-P-07.png',
            './images/가오스형(스텐기본)/JW-P-08.png',
            './images/가오스형(스텐기본)/JW-P-09.png',
            './images/가오스형(스텐기본)/JW-P-10.png',
            './images/가오스형(스텐기본)/주원01.png',
            './images/가오스형(스텐기본)/주원02.png',
            './images/가오스형(스텐기본)/주원03.png',
            './images/가오스형(스텐기본)/주원04.png',
            './images/가오스형(스텐기본)/주원05.png',
            './images/가오스형(스텐기본)/주원06.png',
            './images/가오스형(스텐기본)/주원07.png',
            './images/가오스형(스텐기본)/주원08.png',
            './images/가오스형(스텐기본)/주원09.png',
            './images/가오스형(스텐기본)/주원10.png',
        ],
    },

    // 글로브형(스텐기본)
    {
        id: '글로브형-스텐기본',
        name: '글로브형(스텐기본)',
        category: '글로브형(스텐기본)',
        image: './images/글로브형(스텐기본)/JW-PG-01.png',
        images: [
            './images/글로브형(스텐기본)/JW-PG-01.png',
            './images/글로브형(스텐기본)/JW-PG-02.png',
            './images/글로브형(스텐기본)/JW-PG-03.png',
            './images/글로브형(스텐기본)/JW-PG-04.png',
            './images/글로브형(스텐기본)/JW-PG-05.png',
            './images/글로브형(스텐기본)/JW-PG-06.png',
            './images/글로브형(스텐기본)/JW-PG-07.png',
            './images/글로브형(스텐기본)/JW-PG-08.png',
            './images/글로브형(스텐기본)/JW-PG-09.png',
            './images/글로브형(스텐기본)/JW-PG-10.png',
            './images/글로브형(스텐기본)/주원01.png',
            './images/글로브형(스텐기본)/주원02.png',
            './images/글로브형(스텐기본)/주원03.png',
            './images/글로브형(스텐기본)/주원04.png',
            './images/글로브형(스텐기본)/주원05.png',
            './images/글로브형(스텐기본)/주원06.png',
            './images/글로브형(스텐기본)/주원07.png',
            './images/글로브형(스텐기본)/주원08.png',
            './images/글로브형(스텐기본)/주원09.png',
            './images/글로브형(스텐기본)/주원10.png',
        ],
    },
];
